services:

  web:
    build:
      context: .

    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn cash.wsgi:application
      --bind 0.0.0.0:8000
      --workers 4
      --timeout 120
      "

    env_file:
      - .env

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy

    restart: unless-stopped

    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  db:
    image: mysql:8.4

    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
  static_volume:
  media_volume: