# Generated by Django 6.0.4 on 2026-06-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('youtube_watch', 'Watch YouTube Video'), ('website_visit', 'Visit Website'), ('quiz', 'Quiz'), ('daily_login', 'Daily Login'), ('click_add', 'Click Add')], max_length=30),
        ),
    ]
