# Generated by Django 6.0.4 on 2026-06-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activate_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_wallet',
            field=models.IntegerField(default=0),
        ),
    ]
