# Generated by Django 6.0.4 on 2026-06-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='from_referrals',
            field=models.IntegerField(default=0),
        ),
    ]
