# Generated by Django 6.0.4 on 2026-06-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_from_referrals'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='life_time_earning',
            field=models.IntegerField(default=0),
        ),
    ]
