# Generated by Django 6.0.4 on 2026-06-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notif_types',
            field=models.CharField(choices=[('task', 'task'), ('referral', 'referral'), ('withdrawal', 'withdrawal'), ('system', 'system')], default='system', max_length=30),
        ),
        migrations.AddField(
            model_name='notifications',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
