# Generated by Django 6.0.4 on 2026-06-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0712345678', max_length=15),
        ),
    ]
