# Generated by Django 6.0.4 on 2026-06-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0004_b2ccallbacklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
